/**
 * Corefile generator for the `inspect` engine.
 *
 * Every name a build resolves, allowed or not, is answered locally with the
 * proxy's own address, not NXDOMAIN: the build connects to the proxy and its
 * full URL is recorded before being denied, and a name that is only looked
 * up, never connected to, still shows up in the log. CoreDNS never forwards a
 * query anywhere, so the query itself cannot reach a real nameserver and leak
 * whatever it looked up, with no connection ever needed.
 *
 * Real resolution happens once, in HAProxy, strictly after a request has
 * already passed its full host, path and method check; see
 * haproxy-config.ts. CoreDNS decides nothing a build can reach, only what
 * gets logged as allowed or denied, and that decision still has to match the
 * rules exactly, or a name outside them would be misreported as allowed.
 * That precision is why this engine uses CoreDNS (regex views) over dnsmasq
 * (suffix matching, which could only widen `abc*.amazonaws.com` to
 * `/amazonaws.com/`).
 */

import type { UrlRule } from "./url-rules.ts";
import { wildcardToRegexPartial } from "./partial-wildcard.ts";

export interface CorednsConfigOptions {
  /** Host rules (`host:port` wildcards). Only the host half is used here. */
  httpsRules?: string[];
  httpRules?: string[];
  /** TLS rules. Their names have to resolve too, even though they are not inspected. */
  tlsRules?: string[];
  urlRules?: UrlRule[];
  /** Address every name resolves to, so it lands on the proxy. */
  proxyAddress: string;
  /** TTL for the synthesised answers. */
  ttlSeconds?: number;
  /**
   * `audit` refuses nothing, so every name is logged as allowed. Defaults to
   * `restrict`.
   */
  mode?: "audit" | "restrict";
}

export interface GeneratedCorednsConfig {
  config: string;
  /** Rules whose host could not be derived (`~` regex with a non-literal host). */
  warnings: string[];
}

/**
 * Escape a regex for a CEL string literal.
 *
 * CEL rejects `\.` as an invalid character escape, so every backslash has to
 * be doubled to survive into the regex engine. Substituting only the dots
 * would be wrong: the host compiler escapes every one of `.+^$()[]{}|\`, and a
 * `~` rule may contain any of them.
 */
export function escapeForCel(regex: string): string {
  return regex.replace(/\\/g, "\\\\");
}

/** The host half of a `host:port` wildcard, as a regex. */
function hostRegexOfHostRule(pattern: string): string {
  const combined = wildcardToRegexPartial(pattern);
  return combined.slice(0, combined.lastIndexOf(":"));
}

/** The host half of a compiled URL rule, as a regex. */
function hostRegexOfUrlRule(rule: UrlRule): string | null {
  if (!rule.authorityRegex) return null;
  // authorityRegex is `^<hostRegex>:<port>$`.
  const inner = rule.authorityRegex.slice(1, -1);
  const colonIndex = inner.lastIndexOf(":");
  return colonIndex === -1 ? null : inner.slice(0, colonIndex);
}

/**
 * The lines answering a name with the proxy's own address: NOERROR with an
 * empty AAAA (NODATA), not NXDOMAIN. NXDOMAIN claims the name itself does not
 * exist, and musl's getaddrinfo(AF_UNSPEC) takes that literally and discards
 * the valid A answer along with it, so a build under Alpine (BusyBox wget,
 * apk, ...) would fail outright instead of falling back to the A record like
 * every other resolver does. Shared by every block below, so the answer
 * cannot drift between what an allowed name gets and what a denied one does.
 */
function proxyAnswerLines(proxyAddress: string, ttlSeconds: number): string[] {
  return [
    "    template IN A {",
    `      answer "{{ .Name }} ${ttlSeconds} IN A ${proxyAddress}"`,
    "    }",
    "    template IN AAAA {",
    "    }",
  ];
}

/**
 * Generate a Corefile from buildcage's rules.
 *
 * @throws {Error} if a host rule has invalid wildcard syntax
 */
export function generateCorednsConfig(options: CorednsConfigOptions): GeneratedCorednsConfig {
  const { proxyAddress, ttlSeconds = 60, mode = "restrict" } = options;
  const warnings: string[] = [];
  const hostRegexes: string[] = [];

  // Audit refuses nothing, so every name is logged as allowed. It is still
  // answered locally, not forwarded: audit records what a build tried, it
  // does not need a real answer to do that, and forwarding would make this
  // resolver a live exfiltration channel for any name a build only looks up.
  if (mode === "audit") {
    const lines = [
      "# Generated by buildcage. Do not edit.",
      "",
      "# audit enforces nothing, so every name is logged as allowed. It is still",
      "# answered locally with the proxy's own address, so a name that was only",
      "# looked up, never connected to, still shows up here, and the query",
      "# itself never reaches a real nameserver.",
      ". {",
      ...proxyAnswerLines(proxyAddress, ttlSeconds),
      '    log . "buildcage dns allowed name={name}"',
      "    errors",
      "}",
      "",
    ];
    return { config: lines.join("\n"), warnings };
  }

  const add = (regex: string | null, raw: string) => {
    if (!regex) {
      warnings.push(
        `Rule ${JSON.stringify(raw)} has no derivable host, so the names it targets will not resolve. ` +
          `Add a matching allowed_https_rules entry for the host it targets.`,
      );
      return;
    }
    if (!hostRegexes.includes(regex)) hostRegexes.push(regex);
  };

  for (const rule of options.httpsRules ?? []) add(hostRegexOfHostRule(rule), rule);
  for (const rule of options.httpRules ?? []) add(hostRegexOfHostRule(rule), rule);
  for (const rule of options.tlsRules ?? []) add(hostRegexOfHostRule(rule), rule);
  for (const rule of options.urlRules ?? []) add(hostRegexOfUrlRule(rule), rule.raw);

  const lines: string[] = ["# Generated by buildcage. Do not edit.", ""];

  if (hostRegexes.length > 0) {
    // A queried name arrives with its trailing dot, hence the `[.]` before the
    // anchor. Alternation is used rather than one block per rule so a name is
    // matched against the whole allowlist in one pass.
    const alternation = hostRegexes.map((r) => `(${r})`).join("|");
    lines.push(
      "# Allowlisted names are logged as allowed, but answered exactly like a",
      "# denied one, with the proxy's own address: real resolution happens once",
      "# a request has already passed HAProxy's own host+path+method check, not",
      "# here. The expression is the same host pattern the proxy rules are built",
      "# from, so the two cannot drift apart.",
      ". {",
      "    view allowlist {",
      `      expr name() matches '^(${escapeForCel(alternation)})[.]$'`,
      "    }",
      ...proxyAnswerLines(proxyAddress, ttlSeconds),
      '    log . "buildcage dns allowed name={name}"',
      "    errors",
      "}",
      "",
    );
  }

  lines.push(
    "# Everything else resolves to the proxy and is answered locally, so the",
    "# query never leaves and the request still arrives somewhere its full URL",
    "# can be recorded before being denied.",
    ". {",
    ...proxyAnswerLines(proxyAddress, ttlSeconds),
    '    log . "buildcage dns denied name={name}"',
    "    errors",
    "}",
    "",
  );

  return { config: lines.join("\n"), warnings };
}
