/**
 * haproxy.cfg generator for the `inspect` engine.
 *
 * The config it emits relies on four HAProxy behaviours:
 *
 *  1. One listener takes both TLS and plaintext, told apart by the first bytes
 *     (`req.ssl_hello_type`), so no port is declared in advance and `audit`
 *     records everything unconfigured.
 *  2. The requested name is resolved here, only once the rules below already
 *     allowed the request, and connected to (`do-resolve` then `set-dst`), so
 *     a forged Host or doctored /etc/hosts cannot pick the destination, and a
 *     name a request would be denied for never triggers a real DNS query.
 *     This is the only place a name becomes a real address: the build's own
 *     resolver (CoreDNS) never gives one out; see coredns-config.ts.
 *  3. `..` in the path is resolved before the rules see it (`normalize-uri`).
 *  4. A leaf certificate is generated per SNI, so a refused destination is
 *     never contacted, and the origin certificate is verified on the backend
 *     connection, which is only reached once a request is allowed.
 */

import {
  compileRuleSet,
  HOST_IS_ADDRESS,
  INTERNAL_RANGES,
  type CompiledRule,
  type RuleInputs,
} from "./haproxy-rules.ts";

export interface HaproxyConfigOptions extends RuleInputs {
  /** `audit` records without enforcing, so nothing may be refused. */
  mode?: "restrict" | "audit";
  /** Where redirected traffic arrives. */
  listenPort?: number;
  /**
   * Upstream DNS servers a name is resolved against, once a request has
   * already passed the rule ACLs below. Not the resolver the build itself
   * uses -- CoreDNS never gives out a real answer; see coredns-config.ts.
   */
  resolverAddress?: string[];
  /**
   * The proxy's own address (the CoreDNS/gateway address), excluded from a
   * resolved destination like every other internal range; see
   * INTERNAL_RANGES.
   */
  proxyAddress?: string;
  caSignFile?: string;
  defaultCertFile?: string;
  systemCaFile?: string;
}

const DEFAULTS = {
  listenPort: 10024,
  caSignFile: "/etc/haproxy/ca.pem",
  defaultCertFile: "/etc/haproxy/default.pem",
  systemCaFile: "/etc/ssl/certs/ca-certificates.crt",
};

const TLS_STAGE_PORT = 10025;
const PLAIN_STAGE_PORT = 10026;

export interface GeneratedHaproxyConfig {
  config: string;
  warnings: string[];
}

/** Emit the rule ACLs and the single deny that enforces them. */
function ruleBlock(rules: CompiledRule[], mode: string): string[] {
  const lines: string[] = [];
  if (mode === "audit") {
    lines.push("    # audit records without enforcing, so nothing is refused here.", "");
    return lines;
  }
  if (rules.length === 0) {
    lines.push(
      "    # No rules for this scheme, so nothing is permitted.",
      "    http-request deny",
      "",
    );
    return lines;
  }
  for (const rule of rules) {
    lines.push(`    # ${rule.raw}`);
    // -i, since a name is case-insensitive and do-resolve lowercases anyway.
    lines.push(`    acl ${rule.id}_host hdr(host),host_only -m reg -i ${rule.hostRegex}`);
    if (rule.port) {
      lines.push(`    acl ${rule.id}_port dst_port ${rule.port}`);
    }
    lines.push(`    acl ${rule.id}_path path -m reg ${rule.pathRegex}`);
    if (rule.methods) {
      lines.push(`    acl ${rule.id}_method method ${rule.methods.join(" ")}`);
    }
  }
  lines.push("");
  // Named acls are referenced bare; braces are for anonymous expressions.
  const clauses = rules.map(
    (r) =>
      `${r.id}_host${r.port ? ` ${r.id}_port` : ""} ${r.id}_path` +
      `${r.methods ? ` ${r.id}_method` : ""}`,
  );
  // One deny, negated against every rule: a request matching none is refused.
  lines.push(`    http-request deny unless ${clauses.join(" or ")}`);
  lines.push("");
  return lines;
}

/**
 * Generate a haproxy.cfg from buildcage's rules.
 *
 * @throws {Error} if a host rule has invalid wildcard syntax, or if
 *   resolverAddress is given without proxyAddress
 */
export function generateHaproxyConfig(options: HaproxyConfigOptions = {}): GeneratedHaproxyConfig {
  const opts = { ...DEFAULTS, ...options };
  const {
    https: httpsRules,
    http: httpRules,
    ip: ipRules,
    tls: tlsHosts,
    warnings,
  } = compileRuleSet(options);

  const resolvers = opts.resolverAddress ?? [];
  // Required together, not just individually optional: without proxyAddress
  // here, a name do-resolve sends back to the proxy's own gateway would not
  // be caught by the internal-address guard below, silently rather than
  // loudly. This must fail closed instead of falling through.
  if (resolvers.length > 0 && !opts.proxyAddress) {
    throw new Error("proxyAddress is required whenever resolverAddress is given");
  }
  // The proxy's own address, not the upstream(s) a name is resolved against:
  // see the resolverAddress/proxyAddress doc comments above.
  const dstInternalAddrs = [...INTERNAL_RANGES, ...(opts.proxyAddress ? [opts.proxyAddress] : [])];

  const l: string[] = [];
  l.push(
    "# Generated by buildcage. Do not edit.",
    "",
    "global",
    "    log stdout format raw local0",
    "    # normalize-uri is still marked experimental upstream.",
    "    expose-experimental-directives",
    "    tune.ssl.default-dh-param 2048",
    "",
    "defaults",
    "    log global",
    "    timeout connect 5s",
    "    timeout client 30s",
    "    timeout server 30s",
    "",
  );

  if (resolvers.length > 0) {
    l.push(
      "# Real resolution happens once a request has already passed the rule",
      "# ACLs below; the build's own resolver (CoreDNS) never gives out a real",
      "# answer, so this is the only place a name becomes an address.",
      "resolvers buildcage",
      ...resolvers.map((addr, i) => `    nameserver ns${i + 1} ${addr}:53`),
      "    resolve_retries 3",
      "    timeout resolve 3s",
      "    timeout retry 1s",
      "    hold valid 30s",
      "",
    );
  }

  // --- stage 1: classify ----------------------------------------------------
  l.push(
    "# One listener for everything redirected here. The first bytes say whether",
    "# this is a handshake or a plain request, so no port has to be declared as",
    "# one or the other in advance.",
    "frontend detect",
    `    bind *:${opts.listenPort}`,
    "    mode tcp",
    "    tcp-request inspect-delay 5s",
    "",
  );
  if (ipRules.length > 0 || tlsHosts.length > 0) {
    l.push(
      "    # Captured now, since the request buffer is gone by log time.",
      "    tcp-request content set-var(txn.sni) req.ssl_sni",
      "",
      "    # Passed through untouched: judged before anything is decrypted.",
    );
    for (const rule of ipRules) {
      l.push(`    # ${rule.raw}`);
      l.push(`    acl ${rule.id}_dst dst ${rule.address}`);
      if (rule.port) l.push(`    acl ${rule.id}_port dst_port ${rule.port}`);
    }
    for (const host of tlsHosts) {
      l.push(`    # ${host.raw}`);
      l.push(`    acl ${host.id}_sni req.ssl_sni -m reg -i ${host.hostRegex}`);
      if (host.port) l.push(`    acl ${host.id}_port dst_port ${host.port}`);
    }
    const conds = [
      ...ipRules.map((r) => `${r.id}_dst${r.port ? ` ${r.id}_port` : ""}`),
      ...tlsHosts.map((h) => `${h.id}_sni${h.port ? ` ${h.id}_port` : ""}`),
    ];

    // A passthrough is never decrypted and so has no request line; the name,
    // destination and byte count are logged here, its only record. Flagged
    // before the rules below reject, so a refused passthrough is logged too.
    l.push(
      "",
      "    tcp-request content set-var(txn.pass) int(1) if " + conds.join(" or "),
      "    tcp-request content set-var(txn.proto) str(tls) if { req.ssl_hello_type 1 }",
      "    tcp-request content set-var(txn.proto) str(tcp) unless { req.ssl_hello_type 1 }",
    );

    if (tlsHosts.length > 0 && resolvers.length > 0) {
      // Resolve the SNI ourselves and connect there, as for an inspected
      // request: an SNI is not a destination, so a ClientHello with an allowed
      // name must not become a tunnel to an address of the build's choosing.
      // The flag variable is needed because HAProxy conditions have no
      // grouping: `a or b !c` reads as `a or (b and !c)`.
      l.push("");
      for (const host of tlsHosts) {
        // Ports scope a tls rule (see the ip0/tls0 comment above): without
        // the port ACL here too, an SNI matching a port-scoped rule on a
        // *different* port would still set txn.tlsrule, triggering an early
        // do-resolve/set-dst that overwrites the connection's destination
        // before the inspected path ever sees it, even though txn.pass
        // (gated on sni+port together) correctly never fires for it.
        l.push(
          `    tcp-request content set-var(txn.tlsrule) int(1) if ${host.id}_sni${host.port ? ` ${host.id}_port` : ""}`,
        );
      }
      l.push(
        "    tcp-request content do-resolve(txn.dst,buildcage,ipv4) req.ssl_sni,lower " +
          "if { var(txn.tlsrule) -m found }",
        // Falling through would connect to the address the client chose.
        "    tcp-request content reject if { var(txn.tlsrule) -m found } " +
          "!{ var(txn.dst) -m found }",
        // Before the internal-destination check below, not after, for the
        // same reason and with the same log-format consequence as the
        // inspected path; see the matching comment in stage() below.
        "    tcp-request content set-dst var(txn.dst) if { var(txn.dst) -m found }",
        // Same internal-destination guard as the inspected path; see INTERNAL_RANGES.
        `    acl pass_dst_internal var(txn.dst) -m ip ${dstInternalAddrs.join(" ")}`,
        "    tcp-request content reject if { var(txn.tlsrule) -m found } pass_dst_internal",
      );
    }

    // Only passthroughs log here; the inspected frontends log the request, so
    // logging it here too would double it.
    l.push(
      "",
      "    tcp-request content set-log-level silent unless { var(txn.pass) -m found }",
      `    log-format "buildcage %[date(0,ms)] pass %[var(txn.proto)] sni=%[var(txn.sni)] ` +
        `%B ts=%ts dst=%[dst]:%[dst_port]"`,
      "",
    );
    l.push(`    use_backend passthrough if ${conds.join(" or ")}`, "");
  }
  l.push(
    "    # `accept` ends content-rule evaluation, so it comes after every rule",
    "    # that needs the request buffer (the SNI capture and resolution above).",
    "    tcp-request content accept if { req.ssl_hello_type 1 } || { req.len gt 0 }",
    "",
    "    acl is_tls req.ssl_hello_type 1",
    "    use_backend to_tls if is_tls",
    "    default_backend to_plain",
    "",
    "backend passthrough",
    "    mode tcp",
    "    server origin 0.0.0.0",
    "",
    "backend to_tls",
    "    mode tcp",
    `    server s 127.0.0.1:${TLS_STAGE_PORT} send-proxy-v2`,
    "",
    "backend to_plain",
    "    mode tcp",
    `    server s 127.0.0.1:${PLAIN_STAGE_PORT} send-proxy-v2`,
    "",
  );

  // --- stage 2: inspect -----------------------------------------------------
  const stage = (
    name: string,
    port: number,
    bindExtra: string,
    scheme: string,
    rules: CompiledRule[],
    backend: string,
  ) => {
    l.push(
      `frontend ${name}`,
      `    bind 127.0.0.1:${port} accept-proxy${bindExtra}`,
      "    mode http",
      "    http-request capture req.hdr(host) len 100",
      "",
      "    # Decode before stripping `..`: `.` is unreserved, so `%2e%2e` is not",
      "    # a dot-dot segment until decoded, and stripping first would miss it.",
      "    http-request normalize-uri percent-decode-unreserved",
      "    http-request normalize-uri path-strip-dotdot",
      "",
      "    # pathq, not %HU: %HU is the target as sent (a path over HTTP/1.1, an",
      "    # absolute URI over HTTP/2), and pathq is not readable at log time.",
      "    # Set after normalisation, so the log shows the path the rules matched.",
      "    http-request set-var(txn.pathq) pathq",
      "",
      "    # `%2f` and `%5c` survive decoding (both reserved) yet an origin may",
      "    # read `..%2f` / `..%5c` as a segment, and a raw backslash is not a",
      "    # valid path char at all. None is stripped, so each is refused. A lone",
      "    # encoded separator stays legal (e.g. npm's `/@scope%2fpackage`).",
      "    # `\\\\` is one literal backslash: HAProxy's parser takes the pair as one.",
      "    http-request deny deny_status 403 if { path -m reg -i (^|/|%2f|%5c)\\.\\.($|/|%2f|%5c) }",
      "    http-request deny deny_status 403 if { path -m sub \\\\ }",
      // %ts tells our own refusal (PR / SC) from an origin's own 403 or 503 (--).
      `    log-format "buildcage %[date(0,ms)] ${scheme} %HM ${scheme}://%[capture.req.hdr(0)]%[var(txn.pathq)] %ST %B ts=%ts dst=%[dst]:%[dst_port]"`,
      "",
    );
    // The rules decide first, on the request alone (host, path, method): none
    // of them depend on where the name resolves. Only a request they already
    // allow reaches the do-resolve below, so a name a request would be denied
    // for never triggers a real DNS query -- do-resolve is the only place a
    // real query leaves this proxy, and it must never run ahead of a deny.
    l.push(...ruleBlock(rules, opts.mode ?? "restrict"));
    if (resolvers.length > 0) {
      l.push(
        "    # Connect where WE resolve the Host, discarding the client's address,",
        "    # so a forged Host or doctored /etc/hosts cannot choose the target.",
        "    # host_only drops the port a header carries, which is not part of the",
        "    # name. An address is taken as-is: no resolver can answer one, and the",
        "    # rules above already decided, so nothing is loosened.",
        `    acl host_is_address req.hdr(host),host_only -m reg ${HOST_IS_ADDRESS}`,
        "    http-request set-var(txn.dst) req.hdr(host),host_only if host_is_address",
        "    http-request do-resolve(txn.dst,buildcage,ipv4) req.hdr(host),lower,host_only " +
          "unless host_is_address",
        "    http-request deny deny_status 502 unless { var(txn.dst) -m found }",
        "",
        "    # Set before the internal-destination check below, not after: %[dst] in",
        "    # the log-format is this, and a refusal must show the address that",
        "    # tripped it, not whatever the client's own (fake, unresolved) address",
        "    # was -- CoreDNS never hands out a real one, see coredns-config.ts.",
        "    http-request set-dst var(txn.dst)",
        "",
        "    # A resolved destination may not be internal; see INTERNAL_RANGES. An",
        "    # address named in a rule is exempt.",
        `    acl dst_internal var(txn.dst) -m ip ${dstInternalAddrs.join(" ")}`,
        "    http-request deny deny_status 403 if dst_internal !host_is_address",
        "",
      );
    }
    l.push(`    default_backend ${backend}`, "");
  };

  stage(
    "https_in",
    TLS_STAGE_PORT,
    ` ssl crt ${opts.defaultCertFile} generate-certificates ca-sign-file ${opts.caSignFile}`,
    "https",
    httpsRules,
    "origin_tls",
  );
  stage("http_in", PLAIN_STAGE_PORT, "", "http", httpRules, "origin_plain");

  l.push(
    "# The only place a request reaches the origin, so where its certificate is",
    "# checked; a refused request never gets here. host_only on the SNI, since a",
    "# certificate is verified against a name, not a name and port.",
    "backend origin_tls",
    "    mode http",
    `    server origin 0.0.0.0 ssl verify required ca-file ${opts.systemCaFile} sni req.hdr(host),lower,host_only`,
    "",
    "backend origin_plain",
    "    mode http",
    "    server origin 0.0.0.0",
    "",
  );

  return { config: l.join("\n"), warnings };
}
