/**
 * haproxy.cfg generator for the `inspect` engine.
 *
 * The config it emits relies on four HAProxy behaviors:
 *
 *  1. One listener takes both TLS and plaintext, told apart by the first bytes
 *     (`req.ssl_hello_type`), so no port is declared in advance and `audit`
 *     records everything unconfigured.
 *  2. The requested name is resolved here, only once the rules have already
 *     allowed the request, and connected to (`do-resolve` then `set-dst`), so
 *     a forged Host or doctored /etc/hosts cannot pick the destination, and a
 *     name a request would be denied for never triggers a real DNS query.
 *     This is the only place a name becomes a real address: the build's own
 *     resolver (CoreDNS) never gives one out; see coredns-config.ts.
 *  3. `..` in the path is resolved before the rules see it (`normalize-uri`).
 *  4. A leaf certificate is generated per SNI, so a refused destination is
 *     never contacted, and the origin certificate is verified on the backend
 *     connection, which is only reached once a request is allowed.
 *
 * This file is the wiring: the options, and the order the sections come out
 * in. Each section is generated by its own `haproxy-*.ts` module.
 */

import { compileRuleSet, INTERNAL_RANGES, type RuleInputs } from "./haproxy-rules.ts";
import { PREAMBLE, resolversSection, originBackends } from "./haproxy-sections.ts";
import { detectFrontend } from "./haproxy-detect-frontend.ts";
import { inspectStage } from "./haproxy-inspect-stage.ts";

export interface HaproxyConfigOptions extends RuleInputs {
  /** `audit` records without enforcing, so nothing may be refused. */
  mode?: "restrict" | "audit";
  /** Where redirected traffic arrives. */
  listenPort?: number;
  /**
   * Upstream DNS servers a name is resolved against, once a request has
   * already passed the rule ACLs. Not the resolver the build itself
   * uses, which never gives out a real answer; see coredns-config.ts.
   */
  resolverAddress?: string[];
  /**
   * Resolve through the container's own /etc/resolv.conf rather than named
   * upstreams, so a name resolves against the runner's own DNS. Ignored when
   * resolverAddress names upstreams of its own.
   */
  useResolvConf?: boolean;
  /**
   * The proxy's own address (the CoreDNS/gateway address), excluded from a
   * resolved destination like every other internal range; see
   * INTERNAL_RANGES.
   */
  proxyAddress?: string;
  /**
   * Pattern file of the runner's own addresses, added to the
   * internal-destination guard. A file because HAProxy refuses to start on an
   * acl line past MAX_LINE_ARGS words and the address count is
   * environment-dependent.
   * When omitted, no such acl is emitted.
   */
  hostAddressFile?: string;
  caSignFile?: string;
  defaultCertFile?: string;
  systemCaFile?: string;
}

const DEFAULTS = {
  listenPort: 10024,
  caSignFile: "/etc/haproxy/ca.pem",
  defaultCertFile: "/etc/haproxy/default.pem",
  systemCaFile: "/etc/ssl/certs/ca-certificates.crt",
};

const TLS_STAGE_PORT = 10025;
const PLAIN_STAGE_PORT = 10026;

export interface GeneratedHaproxyConfig {
  config: string;
  warnings: string[];
}

/**
 * Generate a haproxy.cfg from buildcage's rules.
 *
 * @throws {Error} if a host rule has invalid wildcard syntax, or if a resolver
 *   is configured without proxyAddress
 */
export function generateHaproxyConfig(options: HaproxyConfigOptions = {}): GeneratedHaproxyConfig {
  const opts = { ...DEFAULTS, ...options };
  const mode = opts.mode ?? "restrict";
  const {
    https: httpsRules,
    http: httpRules,
    ip: ipRules,
    tls: tlsHosts,
    warnings,
  } = compileRuleSet(options);

  const resolvers = opts.resolverAddress ?? [];
  const useResolvConf = resolvers.length === 0 && opts.useResolvConf === true;
  // Every block below reads this rather than resolvers.length: one left behind
  // would drop do-resolve on the resolv.conf path alone, sending the request
  // wherever the client's own address said.
  const hasResolver = resolvers.length > 0 || useResolvConf;
  // Required together, not just individually optional: without proxyAddress
  // here, a name do-resolve sends back to the proxy's own gateway would pass
  // the internal-address guard below unnoticed, so this fails closed.
  if (hasResolver && !opts.proxyAddress) {
    throw new Error("proxyAddress is required whenever a resolver is configured");
  }

  const shared = {
    hasResolver,
    // The proxy's own address, not the upstream(s) a name is resolved against:
    // a name resolving back to the gateway is as internal as any other.
    internalAddrs: [...INTERNAL_RANGES, ...(opts.proxyAddress ? [opts.proxyAddress] : [])],
    hostAddressFile: opts.hostAddressFile,
  };

  const config = [
    ...PREAMBLE,
    ...(hasResolver ? resolversSection(resolvers, useResolvConf) : []),
    ...detectFrontend({
      listenPort: opts.listenPort,
      tlsStagePort: TLS_STAGE_PORT,
      plainStagePort: PLAIN_STAGE_PORT,
      ipRules,
      tlsHosts,
      proxyAddress: opts.proxyAddress,
      ...shared,
    }),
    ...inspectStage(
      {
        name: "https_in",
        port: TLS_STAGE_PORT,
        bindExtra: ` ssl crt ${opts.defaultCertFile} generate-certificates ca-sign-file ${opts.caSignFile}`,
        scheme: "https",
        rules: httpsRules,
        backend: "origin_tls",
      },
      { mode, ...shared },
    ),
    ...inspectStage(
      {
        name: "http_in",
        port: PLAIN_STAGE_PORT,
        bindExtra: "",
        scheme: "http",
        rules: httpRules,
        backend: "origin_plain",
      },
      { mode, ...shared },
    ),
    ...originBackends(opts.systemCaFile),
  ];

  return { config: config.join("\n"), warnings };
}
