/** What one engine adds to the `global` and `defaults` sections. */
export interface PreambleSpec {
  global: string[];
  defaults: string[];
}

/**
 * Everything ahead of the first frontend that carries traffic. No rule
 * reaches it, so it differs between configs only by engine.
 */
export function preamble(spec: PreambleSpec): string[] {
  return [
    "# Generated by buildcage. Do not edit.",
    "",
    "global",
    // 16384 covers the longest request head haproxy accepts (tune.bufsize -
    // tune.maxrewrite). At the default of 1024 a long URL cuts the line, and a
    // cut line matches nothing at all, taking its event out of the report.
    // `len` must precede `format`, or the config is rejected.
    "    log stdout len 16384 format raw local0",
    // Threads sharing the stdout fd contend for its lock, and the loser drops
    // its line (fd_write_frag_line).
    "    nbthread 1",
    // This process parses traffic the workload controls, so it must not be root.
    "    user haproxy",
    "    group haproxy",
    // Left to its default this follows the runner's own IPv6 route. The ipv4
    // on each do-resolve does not constrain the query; this does. Needs HAProxy
    // 3.2 or newer.
    "    dns-accept-family ipv4",
    ...spec.global,
    "",
    "defaults",
    "    log global",
    "    timeout connect 5s",
    // Lets an idle ssh session, pooled DB connection or WebSocket outlive the
    // client/server timeouts. Each engine's client-fin/server-fin keep closing a
    // half-closed one at those.
    "    timeout tunnel 1h",
    ...spec.defaults,
    "",
    // A unix socket rather than a port, so the readiness check reaching it
    // never depends on what init-iptables allows.
    "# Readiness for s6-notifyoncheck, and the dropped-log count for the report.",
    "# Not reachable from the network.",
    "frontend health",
    "    bind /var/run/haproxy-health.sock mode 666",
    "    mode http",
    "    no log",
    "    monitor-uri /health",
    // A line HAProxy cannot write at once is dropped without a trace in the log
    // itself; only this counter says one went missing.
    "    http-request use-service prometheus-exporter if { path /metrics }",
    "",
  ];
}

/**
 * The resolver every do-resolve uses after the rules allow a connection: the
 * one the container's own /etc/resolv.conf names, as for the runner itself.
 */
export function resolversSection(): string[] {
  return [
    "# Real resolution happens once a request has already passed the rule",
    "# ACLs below; the build's own resolver (CoreDNS) never gives out a real",
    "# answer, so this is the only place a name becomes an address.",
    "resolvers buildcage",
    "    parse-resolv-conf",
    // The only hold do-resolve reads, and it ignores the record's own TTL,
    // so it is also how long a rotated address keeps being dialled. A minute
    // is about the TTL of the hosts a build talks to.
    "    hold valid 60s",
    // One query more than the default, a second apart. On a TLS path they
    // share the frontend's 5s inspect-delay with the wait for the ClientHello.
    "    resolve_retries 4",
    "    timeout retry 1s",
    // The 512-byte default truncates an answer carrying many records, and a
    // truncated answer resolves nothing.
    "    accepted_payload_size 8192",
    "",
  ];
}

/** A gRPC stream can stay silent longer than the 30s inactivity timeouts. */
export const GRPC_REQUEST = "{ req.hdr(content-type) -m beg application/grpc }";

/** The `origin_tls`, `origin_tls_h2` and `origin_plain` backends. */
export function originBackends(systemCaFile: string): string[] {
  const server = `    server origin 0.0.0.0 ssl verify required ca-file ${systemCaFile} sni var(txn.host)`;
  return [
    "# The only place a request reaches the origin, so where its certificate is",
    "# checked; a refused request never gets here. The SNI is the port-free",
    "# txn.host the rules judged, since a certificate is verified against a name,",
    "# not a name and port.",
    "backend origin_tls",
    "    mode http",
    server,
    "",
    "# Only an h2 client's request is offered h2: one from HTTP/1.1 would reach",
    "# the origin with no :authority, which some origins refuse. A WebSocket",
    "# still goes over HTTP/1.1 (`ws auto`), as few origins support RFC 8441.",
    "backend origin_tls_h2",
    "    mode http",
    `    http-request set-timeout server 1h if ${GRPC_REQUEST}`,
    `${server} alpn h2,http/1.1`,
    "",
    "backend origin_plain",
    "    mode http",
    "    server origin 0.0.0.0",
    "",
  ];
}
