import { HOST_ONLY } from "./haproxy-matchers.ts";

/**
 * Everything ahead of the first frontend that carries traffic. No rule and no
 * option reaches it, so it is the same text in every generated config.
 */
export const PREAMBLE: readonly string[] = [
  "# Generated by buildcage. Do not edit.",
  "",
  "global",
  // 16384 covers the longest request head haproxy accepts (tune.bufsize -
  // tune.maxrewrite). At the default of 1024 a long URL cuts the line, and a
  // cut line matches nothing at all, taking its event out of the report.
  // `len` must precede `format`, or the config is rejected.
  "    log stdout len 16384 format raw local0",
  // This process parses traffic the workload controls, so it must not be root.
  "    user haproxy",
  "    group haproxy",
  // Left to its default this follows the runner's own IPv6 route. The ipv4
  // on each do-resolve does not constrain the query; this does. Needs HAProxy
  // 3.2 or newer.
  "    dns-accept-family ipv4",
  "    # normalize-uri is still marked experimental upstream.",
  "    expose-experimental-directives",
  "    tune.ssl.default-dh-param 2048",
  "",
  "defaults",
  "    log global",
  "    timeout connect 5s",
  "    timeout client 30s",
  "    timeout server 30s",
  "",
  // A unix socket rather than a port, so the readiness check reaching it
  // never depends on what init-iptables allows.
  "# Readiness only, for s6-notifyoncheck. Not reachable from the network.",
  "frontend health",
  "    bind /var/run/haproxy-health.sock mode 666",
  "    mode http",
  "    no log",
  "    monitor-uri /health",
  "",
];

/** The resolver both paths do-resolve against, once the rules have allowed. */
export function resolversSection(resolvers: string[], useResolvConf: boolean): string[] {
  return [
    "# Real resolution happens once a request has already passed the rule",
    "# ACLs below; the build's own resolver (CoreDNS) never gives out a real",
    "# answer, so this is the only place a name becomes an address.",
    "resolvers buildcage",
    ...(useResolvConf
      ? ["    parse-resolv-conf"]
      : resolvers.map((addr, i) => `    nameserver ns${i + 1} ${addr}:53`)),
    // The only hold do-resolve reads, and it ignores the record's own TTL,
    // so it is also how long a rotated address keeps being dialled. A minute
    // is about the TTL of the hosts a build talks to.
    "    hold valid 60s",
    // One query more than the default, a second apart. On the passthrough
    // path they share detect's 5s inspect-delay with the wait for the
    // ClientHello.
    "    resolve_retries 4",
    "    timeout retry 1s",
    // The 512-byte default truncates an answer carrying many records, and a
    // truncated answer resolves nothing.
    "    accepted_payload_size 8192",
    "",
  ];
}

/** The `origin_tls` and `origin_plain` backends. */
export function originBackends(systemCaFile: string): string[] {
  return [
    "# The only place a request reaches the origin, so where its certificate is",
    "# checked; a refused request never gets here. host_only on the SNI, since a",
    "# certificate is verified against a name, not a name and port.",
    "backend origin_tls",
    "    mode http",
    `    server origin 0.0.0.0 ssl verify required ca-file ${systemCaFile} sni req.hdr(host),lower,${HOST_ONLY}`,
    "",
    "backend origin_plain",
    "    mode http",
    "    server origin 0.0.0.0",
    "",
  ];
}
